package ru.strict.db.jdbc.util;

import ru.strict.db.core.exception.DatabaseException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.function.Function;

class AutoGeneratedKeyGetter implements Function<PreparedStatement, Object> {
    @Override
    public Object apply(PreparedStatement statement) {
        try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
            if (generatedKeys.next()) {
                 return generatedKeys.getObject(1);
            } else {
                throw new DatabaseException("Creating user failed, no ID obtained");
            }
        } catch (SQLException ex) {
            throw new DatabaseException(ex);
        }
    }
}
